logging:
  level:
    org.springframework: INFO
    com.thoughtworks.xbyi.persona: DEBUG

server:
  port: 8088
  servlet:
    contextPath: /v1/api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persona
    username: root
    password: root
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-master.xml

